apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: spring-grpc/movie-service
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  type: ClusterIP
  selector:
    app: movie-service
  ports:
    - port: 9090
      targetPort: 9090
