grpc:
  client:
    user-service:
      address: static://user-service:9090
      negotiationType: plaintext
    movie-service:
      address: static://movie-service:9090
      negotiationType: plainText
